
project_id = "gohcvgpwuzlepfcucvmj"

[functions.send-reservation-confirmation]
verify_jwt = false

[functions.confirm-reservation]
verify_jwt = false

[functions.send-reservation-email]
verify_jwt = false
