// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gohcvgpwuzlepfcucvmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvaGN2Z3B3dXpsZXBmY3Vjdm1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MzM1NjUsImV4cCI6MjA2NTIwOTU2NX0.zbnu_SrgRQ14yh2yihN2v1HZH67k5J1KNogMY8_j6J8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);